= Mes présentations
Baptiste Mathus <batmat@batmat.net>
:toc: right
:sectanchors:

== A propos de ces présentations

J'ai l'intention d'ajouter autant que possible mes présentations dans ce link:github.com/batmat/presentations[site]. 

Je suis aussi un _bagger_. Si cela vous dit, je peux venir parler des sujets que je connais chez vous entre midi et deux. Pour plus de détails, regardez le site link:http://www.brownbaglunch.fr/baggers.html#Baptiste_Mathus_Toulouse[http://www.brownbaglunch.fr/].

== link:git/prez.html[Git]

== Gerrit
Pour l'instant, disponible uniquement en link:gerrit/prez-gerrit.odp[format OOo .odp]. Je suis en train de convertir en html.

== link:gtd/reveal.js/prez-gtd.html[GTD]

Support utilisé lors de la présentation associée au @ToulouseJug.

== link:50-slides-of-ide/prez.html[50 Slides Of IDE]

Associated support to the link:https://www.eclipsecon.org/france2015/session/50-slides-ide[presentation given for the Eclipse Con 2015].

== Take Your Git Practice To The Next Level

Workshop prepared with link:https://github.com/mpapo[Michaël Pailloncy] for the Eclipse Con France 2015.

This link:http://eclipsecon.org/france2015/session/take-your-git-practice-next-level[workshop has originally been designed] for intermediate users. People who may have started using Git
but are still not very comfortable with it, and want to discover the real power of Git.

* link:git-next-level/prez.html[Presentation]
* link:git-next-level/labs/index.html[Labs Index]
