= Retours ateliers
:toc: right

== TODO

=== A faire pour EclipseCon

* Suite à 3ème repet', ajout de planing timeboxe pour chaque partie sur un adoc à part pour nous servir pendant la prez

=== Ajouter partie eGIT
* Ajouter slide  présentation eGIT/JGit 
* Ajouter démo eGIT / JGIT, au moins petite !
* Ajouter dans le TP rewriting un petit exo pour équivalent "add -p" dans les bonus

=== Corrections 

* Rajouter approfondissements/TP sur .gitattributes (?) dans bonus TP1 (.git) => Batimsse
* Ajouter partie bonus sur submodule/subtree => Batimsse

* Pour chaque TP, ajouter une correction en prefixant les lignes par un "(CORRECTION):" (ou que cela contienne) => Michaël
** chercher une solution existante pour afficher dynamiquement la correction
** une seul fichier adoc de "dev" avec correction inline
** sur le build, séparation en deux fichiers différents pour TP
** vérifier rendering

* Vérifier si on rajoute slide sur les "notes" ou pas ? (est-ce que c'est important )  => Batimsse


=== Corrections TP1 Rewriting : => Batimsse

* Split d'abord footer puis header, sinon le squash va avoir un commit encore sur 2 fichiers
* Attention à tout rebase -i en une fois, sinon tous les sha1 deviennent inutilisables (ou trouver autre chose)
* Pour rebaser un sha x il faut indiquer à -i le parent (au moins)
* Ajouter un conflit sur le cherry-pick du rewriting : faire une gestion de conflit entre 2 fichiers au début (genre merge entre 2 branches ?), est-ce utile à discuter.

=== Correction TP Bisect/Filter branch => Michaël
 
* Guider bcp plus pour les étapes de filter-branch, notamment pour démarrer 




== Historiques déroulement

=== Progress workshop #3

TODO mercredi 17

=== Progress workshop #2
* Start à 12h10
* Début du TP1 12h27
** 12h38 - 10 minutes pour atteindre la 2e partie "... Data Model" (seulement 8 personnes)
** 12h47 : certains ont attaqué le GC
* Pas mal de questions, notamment sur réécriture sans trace :)
* 13h20 : TP rewriting
* 13h48 : on arrête le TP sur le rewriting, pas tout à fait fini mais plutôt ok (faut surtout qu'on revoit le support pour guider encore plus) 
* 13h51 : début TP Bisect & filter-branch

=== Progress workshop #1
* Start à 12h20
* Début du TP1 à 12h38
* Début correction TP1 à 13h01
* FIN correction TP1 à 13h16
* Reprise des slides à partir du #23 à 13h16
* Slide #43 à 13h28
* Start TP2 13h30
* Start correction TP2 13h56
* Fin TP2 14h02

