== Progress workshop #1
* Start à 12h20
* Début du TP1 à 12h38
* Début correction TP1 à 13h01
* FIN correction TP1 à 13h16
* Reprise des slides à partir du #23 à 13h16
* Slide #43 à 13h28
* Start TP2 13h30
* Start correction TP2 13h56
* Fin TP2 14h02

=> Michaël

== TODO

=== A faire pour EclipseCon

* Ajouter partie eGIT / JGIT, au moins petite !

=== Idée à discuter ensemble 

* Rajouter approfondissements/TP sur .gitattributes (?)
** a voir si temps ok => PAS TODO pour demain jeudi 11

=== Corrections de forme et de fond sur les slides

=> Batimsse

* A voir si on peut utiliser http://pcottle.github.io/learnGitBranching/ pour les explications (tester en offline si pas de soucis)
** voir comment le rendre dispo à la fois ang aide aux attendees ET à nous pour éventuellement expliquer en réponse à q°
* Idée évoquée : explication sur "git reset mixed/soft/hard" et "git add -p" ?
** TODO : voir pour reprendre explication orale de Benjamin Marguin avec un diagramme vertical

=== Correction génération des slides 

=> Michaël

* Corriger link/js externes, car la prez s'affiche mal si pas le net 
* Corriger génération des slides pour que ce qui est généré dans _dist soit autonome (pas de dépendance vers ../.deck.js) + vérifier que le rsync copie bien les répertoires/fichiers cachés durant la copie sur la clé

=== Corrections TP1 Git repo :

=> Michaël

* Etape "echo -e "blob 27\0Hi Eclipse Con France 2015" | sha1sum" ne fonctionne pas sur Windows, pas de soucis sur Mac
** TODO : mettre en optionnel et expliquer ce que ça fait pour la suite pr ceux qui peuvent pas l'exécuter.
* Fournir les commandes basiques de création de repo pour gagner du temps (et en général, revoir les TP avec ça en objectif)
** TODO : ajouter git init, git branch en prerequisites/rappel

=== Corrections TP2 Rewriting :

=> Batimsse

* Split d'abord footer puis header, sinon le squash va avoir un commit encore sur 2 fichiers
* Attention à tout rebase -i en une fois, sinon tous les sha1 deviennent inutilisables (ou trouver autre chose)
* Pour rebaser un sha x il faut indiquer à -i le parent (au moins)

* Idée évoquée pendant le TP : faire une gestion de conflit entre 2 fichiers au début (genre merge entre 2 branches ?), est-ce utile à discuter.
** => OK
*** + TP rewriting

TODO global : plus guidé, et ptête supprimer des choses

=== Corrections TP3 Bisect :

=> Michaël

* Mettre moins de test sur le git bisect => 4 voir 5 passages suffisent
** TODO : enlever genre les 100 derniers commits
