== Typing: automatically place semicolons

== Typing: escape text when pasting into a string literal

== Organize imports: how to ignore javadoc

TODO : je ne retrouve pas l'option

== Organize imports ordering

== Formatter: don't touch my manually wrapped lines!

TODO : pas évident

[formatterOnOff]
== Formatter: don't touch that part (using begin/end tags)

[thanks]
link:https://groups.google.com/d/msg/toulouse-jug/EFHt84uEkLk/-OoFV7dopNQJ[Thx Emmanuel Fontan])

== How to quick fix many issues outside of the Clean up menu

Many quick fixes are actually available, but not always through cleanup

[quote]
In Luna (4.4), the multi-fix in the whole file works via Quick Fix hover or via Ctrl+1 popup and then using Ctrl+Enter. To apply the fix to a whole project, you can:
- select the problem in the Problems view
- select the whole project so that the Problems view shows problems from all selected resources
- activate the Problems view again and use Ctrl+1 or context menu > Quick Fix
- select the right fix, click Select All, and click Finish

https://bugs.eclipse.org/bugs/show_bug.cgi?id=351956

== Junit: add -ea to VM arguments..

good way to enable this option but not globally when you may be using libs that added a bunch of incorrect assertions

== Favorites

static imports for autocompletion

== JSR305 annotations to help null analysis

== JSR 305 externally defined annotations

link:https://www.eclipse.org/eclipse/news/4.5/M6/#JDT[JSR305 externally annotated classes (Eclipse Mars)]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=461300

== Save actions: automatic formating

== Overwrite end of method name instead of adding

TODO : Chercher comment : si on rappelle ctrl-espace sur une méthode déjà appelée, écraser jusqu'à la parenthèse à la sélection.

== Automatic contextualization inside an instanceof block (auto-add cast)

== Type filters

to filter out java.awt.* for example...

<<<

filter out method coming from Object! (who wants to call notify...)

== Step filtering
 
Be able to filter out stack when debugging (?) (to be tested)

[thanks]
(thx Sebastien Bordes for the reminder)

== Filtering methods by categorizing them

Categorize Filtering/choosing which methods to display in the _Outline_ using javadoc's _@category_ tags 

[thanks]
(thanks link:https://groups.google.com/d/msg/toulouse-jug/EFHt84uEkLk/Wdf3VMMDM0YJ[Jordi Barrère]).

== _Exception variable name in catch blocks_

== Multi-line Edit

Alt-Shift-A or the icon, as if Sublime Text invented it all ;-)

[thanks]
(link:https://groups.google.com/d/msg/toulouse-jug/SpOWtYPxJa0/tGkr5LAbwU8J[thx Olivier Jaquemet])

== Logical structure

Present complex/weird data structure in a more logical that physical way

see:  link:http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fpreferences%2Fjava%2Fdebug%2Fref-logical_structures.htm[here] 

and link:http://www.javalobby.org/java/forums/t16736.html[here] at least.

== Abreviate package name (Java/Appearance)

== Working Sets

== EGit : staging line by line

== Scrapbooking, REPL

[source,java]
String s = String.format("%05d", 7);
s

https://recoveringprogrammer.wordpress.com/2013/04/06/using-eclipse-scrapbook-to-quickly-test-your-code/

== Add to snippets

== Extensions: SnipMatch

Example: formatter on/off (cf. <<formatterOnOff>>)

== Breakpointing

* conditional
* exception
* class load!

== Conditional breakpoints

Many conditions, not always well-known

<<<

Use it to debug : 

[source,java]
System.out.println("HERE WE ARE: "+theVariable);
return false;

== Clean Up in general

== Clean Up: Convert to lambda expression

== Code templates

Cf. Java/Editor/Templates

== M2E : handling dependencies!

== Autocompleting variable based on types

Type the type and type Ctrl-Space to get proposals about the local variable name.

== Use ';' key to insert method invocation

== Package name abbreviations

Package names in Java views can be abbreviated with custom rules. For example, the following rules produce the rendering shown below:

	org.eclipse.ui={UI}
	org.eclipse.ui.texteditor={T}
	org.eclipse.ui.internal.texteditor=[iT]

== Execute previous run instead of the default value

This way, changing the code it's natural to just run Ctrl-F11 or F11 to re-execute the previously ran test

== Ignore unavoidable generic type problems

== Referring tests

You can find for any class the tests calling it

== Perspectives / Views

TODO : trouver trucs & astuces views/perspectives

== Using p2 Director (inside Docker) to create a customized Eclipse

== asciidoctor in Eclipse

