= Rewriting
:source-language: console
:toc: right

CAUTION: for this workshop, you need to use repository "git-next-level-workshop-rewriting.git" (workshop resources).

== Playing with rebase

=== Tips
TIP: Most instructions below require the use of: 

[source]
git rebase -i <COMMIT SHA>

TIP: When doing an interactive rebase, read what's displayed inside your editor

[source]
----
$ git rebase -i HEAD~
pick 3262d5a ...

# Rebase 0345973..76e0b82 onto 0345973
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented ou
----

=== Rolling back if required

If you want to just rollback any modification you made: use `reflog`, find the previous correct `HEAD` SHA, then reset your working copy to it

    $ git reset --hard <SHA>

=== Let's start

* Open your shell, `cd` to the git workshop repository, list all commits.

CAUTION: Respect the steps order of the following. If you don't, you may change commit SHA-1 and not be able to find the SHA-1 given below.

. The three last commits ("Add jumbotron (partXXX)") are not consistent separately, merge these commits to create only one.
.. (For reference: first commit SHA-1 short version	 = `fc3034f86`)
. Manipulate the two following commits in the same interactive rebase :
.. Commit fe9ba27 is an inconsistent commit. Two different modifications have been made : the first adding a footer and the another correcting the header added in the precedent commit.
.. Commit 05a2231 is a correction of commit fe9ba27 (this sha1 has been changed during precedent action). Merge these two commits to create only one.
Split this commit to move header correction in the precedent commit and keep footer addition in two distinct and consistent commits.
. Commit dbb8f26 has a spelling error. Fix it.

== Playing with dangling commit

Execute this command : 
[source]
git checkout fe9ba27

This commit has been modified during precedent actions. But you can still check it out.

* How does Git keep track of it?
* Explain why.

== Playing with "cherry-pick"

The current repository has a branch named "header-black-experiment".
Execute : 
[source]
git checkout header-black-experiment

* List all commits.
* Using cherry-pick command, try to retrieve commit edcdd0a on the master branch
