= Discovering the .git directory
:source-language: console
:toc: right

NOTE: Use the link:../resources/lab/gitrepository-layout.html[provided documentation if needed]

== ls .git!

* Create a new Git repository (wherever you want)

  git init repo && cd repo && git commit -m 'Initial' --allow-empty

* List the .git directory content and have a look.
* Create a branch _newbranch_, what (and where) did it create inside the .git directory?

  git branch newbranch

* Checkout that branch, then have a look inside `.git/logs/` :
** What is this directory used for?

** Which git command does actually use that directory? 
   (hint: use `git help -a` if needed to find out, then `git help <COMMAND>`)

* Have a look inside `.git/refs`

[source]
ls -l .git/refs/*/*

** What is this directory used for?

== Playing with the data model

In a Git repository, execute precisely the following commands to create a commit with a new file:

[source]
echo "Hi Eclipse Con France 2015" > pof
git add pof
git commit -m "commit done"

If your OS is Linux/Mac based, execute the following command :

[source]
echo -e "blob 27\0Hi Eclipse Con France 2015" | shasum

CAUTION: For Windows users (no `shasum` command available), this command shows that git generates a SHA1 of the committed files to store them in the repository. The result of this command should be `64e3fc24e6ed73f1af43ae4e0411d80c10c4d0f7`

Then execute : 

[source]
git ls-tree master

* What's the role of the ls-tree command?
* Compare the ls-tree output and the echo command output above. Conclude about how Git stores blobs.


* Create a new directory, copy the `pof` file inside it, `git add` the whole directory and commit it. 

[source]
mkdir newdirectory
cp pof newdirectory
git add newdirectory
git commit -m "Added the new subdirectory"

* Use `git ls-tree master` again to understand how the storage works (cf. slides)
* Use `git ls-tree` on the subdirectory to display its content (_hint:_ ls-tree takes a hash as parameter, not directory name). 
** What's the sha of the `pof` in that directory file?

NOTE: There's two categories of Git commands: 
      `porcelain` (example: git `checkout`) and
      `plumbing` (example: git `ls-tree`). These categories actually respectively relate to high-level (user-oriented) and low-level commands. 

TIP: To remember which is one: just remember, in toilets, are you more in contact with the porcelain or the plumbing?

== Garbage collect all the things

NOTE: Having a GC is very hype those days. Git has one too! Git GC will actually execute automatically under some conditions (too many loose/dangling objects, too many branches/tags...). You generally won't run it manually like in the next part.

* Execute `ls .git && ls -l .git/refs/heads` at your test repository root
* Execute `git gc --aggressive --prune=now`
* See what it changed. Explain the goal of the created file.

Ok, hope you enjoyed it, back to slides.
