== Rewriting

NOTE: for this workshop, you need to use repository "git-next-level-workshop-rewriting.git" (workshop resources).

=== Playing with rebase

NOTE: most instructions below need the use of : 
[source]
git rebase -i <COMMIT>

* Located on the git workshop repository, list all commits.
* Commit dbb8f26 has a spelling error. Correct it.
* Commit fe9ba27 is an inconsistent commit. Two different modifications have been made : the first adding a footer and the another correcting the header added in the precedent commit.
Split this commit to move header correction in the precedent commit and keep footer addition in two distinct and consistent commits.
* Commit 05a2231 is a correction of commit fe9ba27 (this sha1 has been changed during precedent action). Merge these two commits to create only one.
* The three last commits ("Add jumbotron (partXXX)") are not consistent separately, merge these commits to create only one.

=== Playing with dangling commit

Execute this command : 
[source]
git checkout fe9ba27

This commit has been modified during precedent actions. 

How Git keeps track on it ?
Explain why.


=== Playing with "cherry-pick"

The current repository has a branch named "header-black-experiment".
Execute : 
[source]
git checkout header-black-experiment

* List all commits.
* Using cherry-pick command, try to retrieve commit edcdd0a on the master branch
